/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Comment {
  'id' : CommentId,
  'createdAt' : Timestamp,
  'text' : string,
  'author' : UserId,
  'postId' : PostId,
}
export type CommentId = bigint;
export interface Post {
  'id' : PostId,
  'likeCount' : bigint,
  'createdAt' : Timestamp,
  'text' : string,
  'likedBy' : Array<UserId>,
  'author' : UserId,
  'updatedAt' : Timestamp,
  'imageUrl' : [] | [string],
}
export type PostId = bigint;
export interface Profile {
  'id' : UserId,
  'bio' : string,
  'username' : [] | [string],
  'contacts' : Array<UserId>,
  'displayName' : string,
  'createdAt' : Timestamp,
  'updatedAt' : Timestamp,
  'avatarUrl' : [] | [string],
}
export type Result = { 'ok' : null } |
  { 'err' : string };
export type Timestamp = bigint;
export type TokenType = { 'ICP' : null } |
  { 'ckBTC' : null } |
  { 'ckETH' : null } |
  { 'ckUSDC' : null } |
  { 'ckUSDT' : null };
export interface Transaction {
  'id' : TxId,
  'status' : TxStatus,
  'token' : TokenType,
  'memo' : [] | [string],
  'counterparty' : Principal,
  'timestamp' : Timestamp,
  'txType' : TxType,
  'amount' : bigint,
}
export type TxId = bigint;
export type TxStatus = { 'pending' : null } |
  { 'completed' : null } |
  { 'failed' : null };
export type TxType = { 'receive' : null } |
  { 'send' : null };
export type UserId = Principal;
export interface _SERVICE {
  'addComment' : ActorMethod<[PostId, string], CommentId>,
  'addContact' : ActorMethod<[string], Result>,
  'createPost' : ActorMethod<[string, [] | [string]], PostId>,
  'createProfile' : ActorMethod<[string, string, [] | [string]], Result>,
  'deleteComment' : ActorMethod<[PostId, CommentId], Result>,
  'deletePost' : ActorMethod<[PostId], Result>,
  'editPost' : ActorMethod<[PostId, string, [] | [string]], Result>,
  'generateInviteLink' : ActorMethod<[string], string>,
  'getAllPosts' : ActorMethod<[], Array<Post>>,
  'getBalance' : ActorMethod<[TokenType], bigint>,
  'getComments' : ActorMethod<[PostId], Array<Comment>>,
  'getContacts' : ActorMethod<[], Array<Profile>>,
  'getInviteProfile' : ActorMethod<[string], [] | [Profile]>,
  'getMyProfile' : ActorMethod<[], [] | [Profile]>,
  'getPost' : ActorMethod<[PostId], [] | [Post]>,
  'getPostsByUser' : ActorMethod<[UserId], Array<Post>>,
  'getProfile' : ActorMethod<[UserId], [] | [Profile]>,
  'getTransactionHistory' : ActorMethod<[], Array<Transaction>>,
  'getUsername' : ActorMethod<[], [] | [string]>,
  'likePost' : ActorMethod<[PostId], Result>,
  'listUsers' : ActorMethod<[], Array<Profile>>,
  'removeContact' : ActorMethod<[UserId], Result>,
  'searchUsers' : ActorMethod<[string], Array<Profile>>,
  'sendToken' : ActorMethod<
    [TokenType, Principal, bigint, [] | [string]],
    Result
  >,
  'setUsername' : ActorMethod<[string], Result>,
  'unlikePost' : ActorMethod<[PostId], Result>,
  'updateProfile' : ActorMethod<[string, string, [] | [string]], Result>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];