/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const PostId = IDL.Nat;
export const CommentId = IDL.Nat;
export const Result = IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text });
export const Timestamp = IDL.Int;
export const UserId = IDL.Principal;
export const Post = IDL.Record({
  'id' : PostId,
  'likeCount' : IDL.Nat,
  'createdAt' : Timestamp,
  'text' : IDL.Text,
  'likedBy' : IDL.Vec(UserId),
  'author' : UserId,
  'updatedAt' : Timestamp,
  'imageUrl' : IDL.Opt(IDL.Text),
});
export const TokenType = IDL.Variant({
  'ICP' : IDL.Null,
  'ckBTC' : IDL.Null,
  'ckETH' : IDL.Null,
  'ckUSDC' : IDL.Null,
  'ckUSDT' : IDL.Null,
});
export const Comment = IDL.Record({
  'id' : CommentId,
  'createdAt' : Timestamp,
  'text' : IDL.Text,
  'author' : UserId,
  'postId' : PostId,
});
export const Profile = IDL.Record({
  'id' : UserId,
  'bio' : IDL.Text,
  'username' : IDL.Opt(IDL.Text),
  'contacts' : IDL.Vec(UserId),
  'displayName' : IDL.Text,
  'createdAt' : Timestamp,
  'updatedAt' : Timestamp,
  'avatarUrl' : IDL.Opt(IDL.Text),
});
export const TxId = IDL.Nat;
export const TxStatus = IDL.Variant({
  'pending' : IDL.Null,
  'completed' : IDL.Null,
  'failed' : IDL.Null,
});
export const TxType = IDL.Variant({ 'receive' : IDL.Null, 'send' : IDL.Null });
export const Transaction = IDL.Record({
  'id' : TxId,
  'status' : TxStatus,
  'token' : TokenType,
  'memo' : IDL.Opt(IDL.Text),
  'counterparty' : IDL.Principal,
  'timestamp' : Timestamp,
  'txType' : TxType,
  'amount' : IDL.Nat,
});

export const idlService = IDL.Service({
  'addComment' : IDL.Func([PostId, IDL.Text], [CommentId], []),
  'addContact' : IDL.Func([IDL.Text], [Result], []),
  'createPost' : IDL.Func([IDL.Text, IDL.Opt(IDL.Text)], [PostId], []),
  'createProfile' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Opt(IDL.Text)],
      [Result],
      [],
    ),
  'deleteComment' : IDL.Func([PostId, CommentId], [Result], []),
  'deletePost' : IDL.Func([PostId], [Result], []),
  'editPost' : IDL.Func([PostId, IDL.Text, IDL.Opt(IDL.Text)], [Result], []),
  'generateInviteLink' : IDL.Func([IDL.Text], [IDL.Text], []),
  'getAllPosts' : IDL.Func([], [IDL.Vec(Post)], ['query']),
  'getBalance' : IDL.Func([TokenType], [IDL.Nat], []),
  'getComments' : IDL.Func([PostId], [IDL.Vec(Comment)], ['query']),
  'getContacts' : IDL.Func([], [IDL.Vec(Profile)], []),
  'getInviteProfile' : IDL.Func([IDL.Text], [IDL.Opt(Profile)], ['query']),
  'getMyProfile' : IDL.Func([], [IDL.Opt(Profile)], []),
  'getPost' : IDL.Func([PostId], [IDL.Opt(Post)], ['query']),
  'getPostsByUser' : IDL.Func([UserId], [IDL.Vec(Post)], ['query']),
  'getProfile' : IDL.Func([UserId], [IDL.Opt(Profile)], ['query']),
  'getTransactionHistory' : IDL.Func([], [IDL.Vec(Transaction)], []),
  'getUsername' : IDL.Func([], [IDL.Opt(IDL.Text)], []),
  'likePost' : IDL.Func([PostId], [Result], []),
  'listUsers' : IDL.Func([], [IDL.Vec(Profile)], ['query']),
  'removeContact' : IDL.Func([UserId], [Result], []),
  'searchUsers' : IDL.Func([IDL.Text], [IDL.Vec(Profile)], ['query']),
  'sendToken' : IDL.Func(
      [TokenType, IDL.Principal, IDL.Nat, IDL.Opt(IDL.Text)],
      [Result],
      [],
    ),
  'setUsername' : IDL.Func([IDL.Text], [Result], []),
  'unlikePost' : IDL.Func([PostId], [Result], []),
  'updateProfile' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Opt(IDL.Text)],
      [Result],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const PostId = IDL.Nat;
  const CommentId = IDL.Nat;
  const Result = IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text });
  const Timestamp = IDL.Int;
  const UserId = IDL.Principal;
  const Post = IDL.Record({
    'id' : PostId,
    'likeCount' : IDL.Nat,
    'createdAt' : Timestamp,
    'text' : IDL.Text,
    'likedBy' : IDL.Vec(UserId),
    'author' : UserId,
    'updatedAt' : Timestamp,
    'imageUrl' : IDL.Opt(IDL.Text),
  });
  const TokenType = IDL.Variant({
    'ICP' : IDL.Null,
    'ckBTC' : IDL.Null,
    'ckETH' : IDL.Null,
    'ckUSDC' : IDL.Null,
    'ckUSDT' : IDL.Null,
  });
  const Comment = IDL.Record({
    'id' : CommentId,
    'createdAt' : Timestamp,
    'text' : IDL.Text,
    'author' : UserId,
    'postId' : PostId,
  });
  const Profile = IDL.Record({
    'id' : UserId,
    'bio' : IDL.Text,
    'username' : IDL.Opt(IDL.Text),
    'contacts' : IDL.Vec(UserId),
    'displayName' : IDL.Text,
    'createdAt' : Timestamp,
    'updatedAt' : Timestamp,
    'avatarUrl' : IDL.Opt(IDL.Text),
  });
  const TxId = IDL.Nat;
  const TxStatus = IDL.Variant({
    'pending' : IDL.Null,
    'completed' : IDL.Null,
    'failed' : IDL.Null,
  });
  const TxType = IDL.Variant({ 'receive' : IDL.Null, 'send' : IDL.Null });
  const Transaction = IDL.Record({
    'id' : TxId,
    'status' : TxStatus,
    'token' : TokenType,
    'memo' : IDL.Opt(IDL.Text),
    'counterparty' : IDL.Principal,
    'timestamp' : Timestamp,
    'txType' : TxType,
    'amount' : IDL.Nat,
  });
  
  return IDL.Service({
    'addComment' : IDL.Func([PostId, IDL.Text], [CommentId], []),
    'addContact' : IDL.Func([IDL.Text], [Result], []),
    'createPost' : IDL.Func([IDL.Text, IDL.Opt(IDL.Text)], [PostId], []),
    'createProfile' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Opt(IDL.Text)],
        [Result],
        [],
      ),
    'deleteComment' : IDL.Func([PostId, CommentId], [Result], []),
    'deletePost' : IDL.Func([PostId], [Result], []),
    'editPost' : IDL.Func([PostId, IDL.Text, IDL.Opt(IDL.Text)], [Result], []),
    'generateInviteLink' : IDL.Func([IDL.Text], [IDL.Text], []),
    'getAllPosts' : IDL.Func([], [IDL.Vec(Post)], ['query']),
    'getBalance' : IDL.Func([TokenType], [IDL.Nat], []),
    'getComments' : IDL.Func([PostId], [IDL.Vec(Comment)], ['query']),
    'getContacts' : IDL.Func([], [IDL.Vec(Profile)], []),
    'getInviteProfile' : IDL.Func([IDL.Text], [IDL.Opt(Profile)], ['query']),
    'getMyProfile' : IDL.Func([], [IDL.Opt(Profile)], []),
    'getPost' : IDL.Func([PostId], [IDL.Opt(Post)], ['query']),
    'getPostsByUser' : IDL.Func([UserId], [IDL.Vec(Post)], ['query']),
    'getProfile' : IDL.Func([UserId], [IDL.Opt(Profile)], ['query']),
    'getTransactionHistory' : IDL.Func([], [IDL.Vec(Transaction)], []),
    'getUsername' : IDL.Func([], [IDL.Opt(IDL.Text)], []),
    'likePost' : IDL.Func([PostId], [Result], []),
    'listUsers' : IDL.Func([], [IDL.Vec(Profile)], ['query']),
    'removeContact' : IDL.Func([UserId], [Result], []),
    'searchUsers' : IDL.Func([IDL.Text], [IDL.Vec(Profile)], ['query']),
    'sendToken' : IDL.Func(
        [TokenType, IDL.Principal, IDL.Nat, IDL.Opt(IDL.Text)],
        [Result],
        [],
      ),
    'setUsername' : IDL.Func([IDL.Text], [Result], []),
    'unlikePost' : IDL.Func([PostId], [Result], []),
    'updateProfile' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Opt(IDL.Text)],
        [Result],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };