/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export type UserId = Principal;
export type Timestamp = bigint;
export type Result = {
    __kind__: "ok";
    ok: null;
} | {
    __kind__: "err";
    err: string;
};
export type CommentId = bigint;
export interface Comment {
    id: CommentId;
    createdAt: Timestamp;
    text: string;
    author: UserId;
    postId: PostId;
}
export type TxId = bigint;
export type PostId = bigint;
export interface Post {
    id: PostId;
    likeCount: bigint;
    createdAt: Timestamp;
    text: string;
    likedBy: Array<UserId>;
    author: UserId;
    updatedAt: Timestamp;
    imageUrl?: string;
}
export interface Profile {
    id: UserId;
    bio: string;
    username?: string;
    contacts: Array<UserId>;
    displayName: string;
    createdAt: Timestamp;
    updatedAt: Timestamp;
    avatarUrl?: string;
}
export interface Transaction {
    id: TxId;
    status: TxStatus;
    token: TokenType;
    memo?: string;
    counterparty: Principal;
    timestamp: Timestamp;
    txType: TxType;
    amount: bigint;
}
export enum TokenType {
    ICP = "ICP",
    ckBTC = "ckBTC",
    ckETH = "ckETH",
    ckUSDC = "ckUSDC",
    ckUSDT = "ckUSDT"
}
export enum TxStatus {
    pending = "pending",
    completed = "completed",
    failed = "failed"
}
export enum TxType {
    receive = "receive",
    send = "send"
}
export interface backendInterface {
    addComment(postId: PostId, text: string): Promise<CommentId>;
    addContact(username: string): Promise<Result>;
    createPost(text: string, imageUrl: string | null): Promise<PostId>;
    createProfile(displayName: string, bio: string, avatarUrl: string | null): Promise<Result>;
    deleteComment(postId: PostId, commentId: CommentId): Promise<Result>;
    deletePost(postId: PostId): Promise<Result>;
    editPost(postId: PostId, text: string, imageUrl: string | null): Promise<Result>;
    generateInviteLink(username: string): Promise<string>;
    getAllPosts(): Promise<Array<Post>>;
    getBalance(token: TokenType): Promise<bigint>;
    getComments(postId: PostId): Promise<Array<Comment>>;
    getContacts(): Promise<Array<Profile>>;
    getInviteProfile(username: string): Promise<Profile | null>;
    getMyProfile(): Promise<Profile | null>;
    getPost(id: PostId): Promise<Post | null>;
    getPostsByUser(userId: UserId): Promise<Array<Post>>;
    getProfile(userId: UserId): Promise<Profile | null>;
    getTransactionHistory(): Promise<Array<Transaction>>;
    getUsername(): Promise<string | null>;
    likePost(postId: PostId): Promise<Result>;
    listUsers(): Promise<Array<Profile>>;
    removeContact(userId: UserId): Promise<Result>;
    searchUsers(searchTerm: string): Promise<Array<Profile>>;
    sendToken(token: TokenType, to: Principal, amount: bigint, memo: string | null): Promise<Result>;
    setUsername(username: string): Promise<Result>;
    unlikePost(postId: PostId): Promise<Result>;
    updateProfile(displayName: string, bio: string, avatarUrl: string | null): Promise<Result>;
}
import type { Post as _Post, PostId as _PostId, Profile as _Profile, Result as _Result, Timestamp as _Timestamp, TokenType as _TokenType, Transaction as _Transaction, TxId as _TxId, TxStatus as _TxStatus, TxType as _TxType, UserId as _UserId } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async addComment(arg0: PostId, arg1: string): Promise<CommentId> {
        if (this.processError) {
            try {
                const result = await this.actor.addComment(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addComment(arg0, arg1);
            return result;
        }
    }
    async addContact(arg0: string): Promise<Result> {
        if (this.processError) {
            try {
                const result = await this.actor.addContact(arg0);
                return from_candid_Result_n1(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addContact(arg0);
            return from_candid_Result_n1(this._uploadFile, this._downloadFile, result);
        }
    }
    async createPost(arg0: string, arg1: string | null): Promise<PostId> {
        if (this.processError) {
            try {
                const result = await this.actor.createPost(arg0, to_candid_opt_n3(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createPost(arg0, to_candid_opt_n3(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async createProfile(arg0: string, arg1: string, arg2: string | null): Promise<Result> {
        if (this.processError) {
            try {
                const result = await this.actor.createProfile(arg0, arg1, to_candid_opt_n3(this._uploadFile, this._downloadFile, arg2));
                return from_candid_Result_n1(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createProfile(arg0, arg1, to_candid_opt_n3(this._uploadFile, this._downloadFile, arg2));
            return from_candid_Result_n1(this._uploadFile, this._downloadFile, result);
        }
    }
    async deleteComment(arg0: PostId, arg1: CommentId): Promise<Result> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteComment(arg0, arg1);
                return from_candid_Result_n1(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteComment(arg0, arg1);
            return from_candid_Result_n1(this._uploadFile, this._downloadFile, result);
        }
    }
    async deletePost(arg0: PostId): Promise<Result> {
        if (this.processError) {
            try {
                const result = await this.actor.deletePost(arg0);
                return from_candid_Result_n1(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deletePost(arg0);
            return from_candid_Result_n1(this._uploadFile, this._downloadFile, result);
        }
    }
    async editPost(arg0: PostId, arg1: string, arg2: string | null): Promise<Result> {
        if (this.processError) {
            try {
                const result = await this.actor.editPost(arg0, arg1, to_candid_opt_n3(this._uploadFile, this._downloadFile, arg2));
                return from_candid_Result_n1(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.editPost(arg0, arg1, to_candid_opt_n3(this._uploadFile, this._downloadFile, arg2));
            return from_candid_Result_n1(this._uploadFile, this._downloadFile, result);
        }
    }
    async generateInviteLink(arg0: string): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.generateInviteLink(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.generateInviteLink(arg0);
            return result;
        }
    }
    async getAllPosts(): Promise<Array<Post>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllPosts();
                return from_candid_vec_n4(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllPosts();
            return from_candid_vec_n4(this._uploadFile, this._downloadFile, result);
        }
    }
    async getBalance(arg0: TokenType): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.getBalance(to_candid_TokenType_n8(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getBalance(to_candid_TokenType_n8(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async getComments(arg0: PostId): Promise<Array<Comment>> {
        if (this.processError) {
            try {
                const result = await this.actor.getComments(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getComments(arg0);
            return result;
        }
    }
    async getContacts(): Promise<Array<Profile>> {
        if (this.processError) {
            try {
                const result = await this.actor.getContacts();
                return from_candid_vec_n10(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getContacts();
            return from_candid_vec_n10(this._uploadFile, this._downloadFile, result);
        }
    }
    async getInviteProfile(arg0: string): Promise<Profile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getInviteProfile(arg0);
                return from_candid_opt_n13(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getInviteProfile(arg0);
            return from_candid_opt_n13(this._uploadFile, this._downloadFile, result);
        }
    }
    async getMyProfile(): Promise<Profile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getMyProfile();
                return from_candid_opt_n13(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMyProfile();
            return from_candid_opt_n13(this._uploadFile, this._downloadFile, result);
        }
    }
    async getPost(arg0: PostId): Promise<Post | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getPost(arg0);
                return from_candid_opt_n14(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPost(arg0);
            return from_candid_opt_n14(this._uploadFile, this._downloadFile, result);
        }
    }
    async getPostsByUser(arg0: UserId): Promise<Array<Post>> {
        if (this.processError) {
            try {
                const result = await this.actor.getPostsByUser(arg0);
                return from_candid_vec_n4(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPostsByUser(arg0);
            return from_candid_vec_n4(this._uploadFile, this._downloadFile, result);
        }
    }
    async getProfile(arg0: UserId): Promise<Profile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getProfile(arg0);
                return from_candid_opt_n13(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getProfile(arg0);
            return from_candid_opt_n13(this._uploadFile, this._downloadFile, result);
        }
    }
    async getTransactionHistory(): Promise<Array<Transaction>> {
        if (this.processError) {
            try {
                const result = await this.actor.getTransactionHistory();
                return from_candid_vec_n15(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getTransactionHistory();
            return from_candid_vec_n15(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUsername(): Promise<string | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUsername();
                return from_candid_opt_n7(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUsername();
            return from_candid_opt_n7(this._uploadFile, this._downloadFile, result);
        }
    }
    async likePost(arg0: PostId): Promise<Result> {
        if (this.processError) {
            try {
                const result = await this.actor.likePost(arg0);
                return from_candid_Result_n1(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.likePost(arg0);
            return from_candid_Result_n1(this._uploadFile, this._downloadFile, result);
        }
    }
    async listUsers(): Promise<Array<Profile>> {
        if (this.processError) {
            try {
                const result = await this.actor.listUsers();
                return from_candid_vec_n10(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listUsers();
            return from_candid_vec_n10(this._uploadFile, this._downloadFile, result);
        }
    }
    async removeContact(arg0: UserId): Promise<Result> {
        if (this.processError) {
            try {
                const result = await this.actor.removeContact(arg0);
                return from_candid_Result_n1(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.removeContact(arg0);
            return from_candid_Result_n1(this._uploadFile, this._downloadFile, result);
        }
    }
    async searchUsers(arg0: string): Promise<Array<Profile>> {
        if (this.processError) {
            try {
                const result = await this.actor.searchUsers(arg0);
                return from_candid_vec_n10(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.searchUsers(arg0);
            return from_candid_vec_n10(this._uploadFile, this._downloadFile, result);
        }
    }
    async sendToken(arg0: TokenType, arg1: Principal, arg2: bigint, arg3: string | null): Promise<Result> {
        if (this.processError) {
            try {
                const result = await this.actor.sendToken(to_candid_TokenType_n8(this._uploadFile, this._downloadFile, arg0), arg1, arg2, to_candid_opt_n3(this._uploadFile, this._downloadFile, arg3));
                return from_candid_Result_n1(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.sendToken(to_candid_TokenType_n8(this._uploadFile, this._downloadFile, arg0), arg1, arg2, to_candid_opt_n3(this._uploadFile, this._downloadFile, arg3));
            return from_candid_Result_n1(this._uploadFile, this._downloadFile, result);
        }
    }
    async setUsername(arg0: string): Promise<Result> {
        if (this.processError) {
            try {
                const result = await this.actor.setUsername(arg0);
                return from_candid_Result_n1(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.setUsername(arg0);
            return from_candid_Result_n1(this._uploadFile, this._downloadFile, result);
        }
    }
    async unlikePost(arg0: PostId): Promise<Result> {
        if (this.processError) {
            try {
                const result = await this.actor.unlikePost(arg0);
                return from_candid_Result_n1(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.unlikePost(arg0);
            return from_candid_Result_n1(this._uploadFile, this._downloadFile, result);
        }
    }
    async updateProfile(arg0: string, arg1: string, arg2: string | null): Promise<Result> {
        if (this.processError) {
            try {
                const result = await this.actor.updateProfile(arg0, arg1, to_candid_opt_n3(this._uploadFile, this._downloadFile, arg2));
                return from_candid_Result_n1(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateProfile(arg0, arg1, to_candid_opt_n3(this._uploadFile, this._downloadFile, arg2));
            return from_candid_Result_n1(this._uploadFile, this._downloadFile, result);
        }
    }
}
function from_candid_Post_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Post): Post {
    return from_candid_record_n6(_uploadFile, _downloadFile, value);
}
function from_candid_Profile_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Profile): Profile {
    return from_candid_record_n12(_uploadFile, _downloadFile, value);
}
function from_candid_Result_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Result): Result {
    return from_candid_variant_n2(_uploadFile, _downloadFile, value);
}
function from_candid_TokenType_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _TokenType): TokenType {
    return from_candid_variant_n21(_uploadFile, _downloadFile, value);
}
function from_candid_Transaction_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Transaction): Transaction {
    return from_candid_record_n17(_uploadFile, _downloadFile, value);
}
function from_candid_TxStatus_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _TxStatus): TxStatus {
    return from_candid_variant_n19(_uploadFile, _downloadFile, value);
}
function from_candid_TxType_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _TxType): TxType {
    return from_candid_variant_n23(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Profile]): Profile | null {
    return value.length === 0 ? null : from_candid_Profile_n11(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Post]): Post | null {
    return value.length === 0 ? null : from_candid_Post_n5(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [string]): string | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _UserId;
    bio: string;
    username: [] | [string];
    contacts: Array<_UserId>;
    displayName: string;
    createdAt: _Timestamp;
    updatedAt: _Timestamp;
    avatarUrl: [] | [string];
}): {
    id: UserId;
    bio: string;
    username?: string;
    contacts: Array<UserId>;
    displayName: string;
    createdAt: Timestamp;
    updatedAt: Timestamp;
    avatarUrl?: string;
} {
    return {
        id: value.id,
        bio: value.bio,
        username: record_opt_to_undefined(from_candid_opt_n7(_uploadFile, _downloadFile, value.username)),
        contacts: value.contacts,
        displayName: value.displayName,
        createdAt: value.createdAt,
        updatedAt: value.updatedAt,
        avatarUrl: record_opt_to_undefined(from_candid_opt_n7(_uploadFile, _downloadFile, value.avatarUrl))
    };
}
function from_candid_record_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _TxId;
    status: _TxStatus;
    token: _TokenType;
    memo: [] | [string];
    counterparty: Principal;
    timestamp: _Timestamp;
    txType: _TxType;
    amount: bigint;
}): {
    id: TxId;
    status: TxStatus;
    token: TokenType;
    memo?: string;
    counterparty: Principal;
    timestamp: Timestamp;
    txType: TxType;
    amount: bigint;
} {
    return {
        id: value.id,
        status: from_candid_TxStatus_n18(_uploadFile, _downloadFile, value.status),
        token: from_candid_TokenType_n20(_uploadFile, _downloadFile, value.token),
        memo: record_opt_to_undefined(from_candid_opt_n7(_uploadFile, _downloadFile, value.memo)),
        counterparty: value.counterparty,
        timestamp: value.timestamp,
        txType: from_candid_TxType_n22(_uploadFile, _downloadFile, value.txType),
        amount: value.amount
    };
}
function from_candid_record_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _PostId;
    likeCount: bigint;
    createdAt: _Timestamp;
    text: string;
    likedBy: Array<_UserId>;
    author: _UserId;
    updatedAt: _Timestamp;
    imageUrl: [] | [string];
}): {
    id: PostId;
    likeCount: bigint;
    createdAt: Timestamp;
    text: string;
    likedBy: Array<UserId>;
    author: UserId;
    updatedAt: Timestamp;
    imageUrl?: string;
} {
    return {
        id: value.id,
        likeCount: value.likeCount,
        createdAt: value.createdAt,
        text: value.text,
        likedBy: value.likedBy,
        author: value.author,
        updatedAt: value.updatedAt,
        imageUrl: record_opt_to_undefined(from_candid_opt_n7(_uploadFile, _downloadFile, value.imageUrl))
    };
}
function from_candid_variant_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    pending: null;
} | {
    completed: null;
} | {
    failed: null;
}): TxStatus {
    return "pending" in value ? TxStatus.pending : "completed" in value ? TxStatus.completed : "failed" in value ? TxStatus.failed : value;
}
function from_candid_variant_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: null;
} | {
    err: string;
}): {
    __kind__: "ok";
    ok: null;
} | {
    __kind__: "err";
    err: string;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: value.ok
    } : "err" in value ? {
        __kind__: "err",
        err: value.err
    } : value;
}
function from_candid_variant_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ICP: null;
} | {
    ckBTC: null;
} | {
    ckETH: null;
} | {
    ckUSDC: null;
} | {
    ckUSDT: null;
}): TokenType {
    return "ICP" in value ? TokenType.ICP : "ckBTC" in value ? TokenType.ckBTC : "ckETH" in value ? TokenType.ckETH : "ckUSDC" in value ? TokenType.ckUSDC : "ckUSDT" in value ? TokenType.ckUSDT : value;
}
function from_candid_variant_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    receive: null;
} | {
    send: null;
}): TxType {
    return "receive" in value ? TxType.receive : "send" in value ? TxType.send : value;
}
function from_candid_vec_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Profile>): Array<Profile> {
    return value.map((x)=>from_candid_Profile_n11(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Transaction>): Array<Transaction> {
    return value.map((x)=>from_candid_Transaction_n16(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Post>): Array<Post> {
    return value.map((x)=>from_candid_Post_n5(_uploadFile, _downloadFile, x));
}
function to_candid_TokenType_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: TokenType): _TokenType {
    return to_candid_variant_n9(_uploadFile, _downloadFile, value);
}
function to_candid_opt_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: string | null): [] | [string] {
    return value === null ? candid_none() : candid_some(value);
}
function to_candid_variant_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: TokenType): {
    ICP: null;
} | {
    ckBTC: null;
} | {
    ckETH: null;
} | {
    ckUSDC: null;
} | {
    ckUSDT: null;
} {
    return value == TokenType.ICP ? {
        ICP: null
    } : value == TokenType.ckBTC ? {
        ckBTC: null
    } : value == TokenType.ckETH ? {
        ckETH: null
    } : value == TokenType.ckUSDC ? {
        ckUSDC: null
    } : value == TokenType.ckUSDT ? {
        ckUSDT: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
